### ISSUE TITLE
Add support for client timezone information

### ISSUE THREAD

**Issue by fmrsabino** [safe-global/safe-client-gateway#1024]
If the user is in a timezone that follows daylight saving, the transaction history grouping is done without taking it into consideration.

# Problem

If a user is in a  UTC+1 timezone (winter) and UTC+2 (summer), a transaction done during daylight savings will be incorrectly grouped when daylight savings are not observed.

When daylight savings is not being observed, the clients send a UTC+1 difference in milliseconds (3600000 ms). The Safe Client Gateway will then create transaction groups taking only the `3600000` shift into consideration.

If the clients use a solution that takes daylight savings into consideration, this might cause some transactions to be rendered with UTC+2 and potentially making the group that was created with UTC+1 to contain transactions of the following/previous day.

# Example

- TX1 done on `Sun Jul 30 2023 22:46:47 UTC+0000`.
- TX2 done on `Sun Jul 30 2023 21:46:47 UTC+0000`
- Client on UTC+1 Winter, UTC+2 Summer
- Client is on Winter timezone

1. Client sends timezone offset of +1 hour
2. CGW computes groups with 1 hour difference.
3. CGW returns a group with July 30 (22:46:47 UTC+0000) with transactions TX1 and TX2
4. Clients, aware of daylight savings, shift the header label to July 31 (00:46:47 UTC+2) that will include TX1 and TX2 while there should be two groups rendered: July 31 with TX1 and July 30 with TX2.

The transaction was therefore shifted to a different day on the client side while it should've been grouped correctly on the CGW side.

# Expected Result

Given the same example as the one above:
1. Client sends timezone offset of +1 hour
2. CGW computes groups with 1 hour difference **and takes into consideration daylight savings**. 
3. CGW returns two groups:
  * July 30 (22:46:47 UTC+0000) with TX1 
  * July 30 (21:46:47 UTC+0000) with TX2
5. Clients, aware of daylight savings, shift the first header label to July 31 (00:46:47 UTC+2) which includes TX1.

**Comment by DmitryBespalov** [comment]
From https://github.com/safe-global/safe-client-gateway/issues/924#issuecomment-2270889249:

> Researching the UTC and DST (daylight saving time), it seems that the best way to resolved the issue with DST is to use the `timezone ID`, like `Europe/Paris` instead of the `timezone_offset` (`+1:00`). This way, backend gets full information about the timezone from the clients, including the DST adjustment. If the timezone ID is not available then we can fall back to the timezone offset.
> 
> References: https://tc39.es/proposal-temporal/docs/ambiguity.html#understanding-time-zones-offset-changes-and-dst https://tc39.es/proposal-temporal/docs/ambiguity.html#ambiguity-due-to-dst-or-other-time-zone-offset-changes
