### ISSUE TITLE
500 error returned on query transactions by id

### ISSUE THREAD

**Issue by moisses89** [safe-global/safe-client-gateway#1033]
**Describe the bug**
Get transactions by id are returning 500 error when the transaction contents more than 200 operations inside.

**To Reproduce**
- Call GET `/v1/chains/1/transactions/ethereum_<details_id>` where details_id corresponds with a transaction with more than 200 operations.
- Error 500 is returned and the following body:
```
{
  "code": 1337,
  "message": "No transfer found"
}
```
**Expected behavior**
Return 200 or 404 but 500 is not expected.

**Comment by fmrsabino** [comment]
Since we started using a unique id for transfers and module transactions, this issue no longer applies.
