### ISSUE TITLE
Build an ARM image on CI execution

### ISSUE THREAD

**Issue by hectorgomezv** [safe-global/safe-client-gateway#1061]
For both testing purposes, we'd like to build ARM docker images in our CI pipeline along with the current x86 images.
For reference, see the Safe Transaction Service CI: https://github.com/safe-global/safe-transaction-service/blob/master/.github/workflows/python.yml

Also note it seems to be necessary to set up QEMU in order to build the ARM images (thanks @Uxio0):
```
- uses: docker/setup-qemu-action@v2
```

Expected outcome:
- ARM Docker images should be built and uploaded to the registry.

**Comment by fmrsabino** [comment]
ARM images are being provided for both the Rust implementation and the [NodeJS one](https://github.com/safe-global/safe-client-gateway-nest). Closing the issue.
