### ISSUE TITLE
dataDecoded=null

### ISSUE THREAD

**Issue by mhxw** [safe-global/safe-client-gateway#1088]
**Describe the bug**
call cgw url , dataDecoded=null

**To Reproduce**
- Call url `ip:port/v1/chains/<chain_id>/transactions/<transaction_id>`
- Provide `json` you are submitting to the service (if it applies)
![image](https://user-images.githubusercontent.com/32643286/225543123-edb05e49-35be-4bed-a571-ab9f2b2a5a1b.png)

- Links to issues in other repos (if possible)
https://github.com/safe-global/safe-infrastructure/issues/77

**Expected behavior**

I queried through txs api/v1/data-decoder/api that dataDecoded is valuable.I hope to find out through the CGW URL that it also has a value.
![image](https://user-images.githubusercontent.com/32643286/225544013-ce8e2bd9-92e6-4837-8043-4ac2b021cee3.png)

**Environment (please complete the following information):**
 - Browser [ chrome]
 - Version [ 3.51.0 ]

**Additional context**
 cgw.env `FEATURE_FLAG_NESTED_DECODING=true`; is set

**Comment by hectorgomezv** [comment]
Closing this as it's duplicated by https://github.com/safe-global/safe-infrastructure/issues/77, we can continue there 🙂
