### ISSUE TITLE
Remove v1 collectibles endpoint

### ISSUE THREAD

**Issue by hectorgomezv** [safe-global/safe-client-gateway#1098]
`/v1/chains/<chain_id>/safes/<safe_address>/collectibles` shouldn't be available anymore, since the provider (Transaction Service) has deprecated the related endpoint. 

**Solution**
Two options here:
- Remove the endpoint completely (including Swagger specification).
- Keep the endpoint but send a deprecation note to the clients indicating the new endpoint to use (v2).

**Comment by fmrsabino** [comment]
The V1 collectibles endpoint was removed in the migration to https://github.com/safe-global/safe-client-gateway-nest
