### ISSUE TITLE
Cancellation `timestamp` not returned correctly

### ISSUE THREAD

**Issue by iamacook** [safe-global/safe-client-gateway#1118]
**Describe the bug**
The cancellation `timestamp` is not returned correctly.

When a transaction has the `txStatus` of `CANCELLED`, the `timestamp` is of creation, not cancellation.

**To Reproduce**

- Create and cancel a transaction, observing the incorrect `timestamp`.
- [Example transaction](https://safe-client.safe.global/v1/chains/100/transactions/multisig_0x9DF58F04F3e914ED8D972146401C85313A53FecA_0xf46cbeeb673201593a8ffae2caa7ffb7877fc3671599c96f6135993271e924b9).

**Expected behavior**

The `timestamp` of a cancelled transaction returns the timestamp of cancellation.

**Comment by fmrsabino** [comment]
@iamacook With the recent migration is this something that we still need to tackle? (I can transfer the issue)

**Comment by iamacook** [comment]
> @iamacook With the recent migration is this something that we still need to tackle? (I can transfer the issue)

It's no longer relevant from what I can tell so I will close it.
