### ISSUE TITLE
Remove/reduce caching of owners endpoint

### ISSUE THREAD

**Issue by iamacook** [safe-global/safe-client-gateway#1183]
The owners endpoint [has no invalidation hook](https://github.com/safe-global/safe-client-gateway/blob/main/src/datasources/transaction-api/transaction-api.service.ts#L653-L655) and therefore caches until expiration.

We chould either remove/reduce caching as the client requires this endpoint for the UI. If the owners array was sent with the Safe creation event, we could alternatively invalidate the cache via that.

**Comment by fmrsabino** [comment]
Given that we don't have invalidation hooks for this event I would not cache these entries. An alternative solution would be to have it configurable via an environment variable if we see that we need to mitigate the number of calls to the endpoints behind this route.

The long-term solution would involve being able to deterministically get the associated keys for events that we already process (e.g.: `EXECUTED_MULTISIG_TRANSACTION`).
