### ISSUE TITLE
Validate address checksums for Email routes

### ISSUE THREAD

**Issue by iamacook** [safe-global/safe-client-gateway#1190]
We should ensure addresses are checksummed for consistency and eventual comparison on the route level (as done [on the Transaction Servce](https://github.com/safe-global/safe-transaction-service/blob/913abe38f3b46d1391334c497848b48655b56897/safe_transaction_service/history/tests/test_views.py#L1204-L1207)). We should also coerce those from datasources.

**Comment by fmrsabino** [comment]
We should probably limit the scope of this ticket to routes that deal with case-sensitive data sources (such as Postgres) as this change might not be required across all the different routes.
