### ISSUE TITLE
Add meta robots noindex for Swagger dev/staging URL

### ISSUE THREAD

**Issue by DiogoSoaress** [safe-global/safe-client-gateway#1224]
### Description

PR, dev and staging deployments are being unnecessarily indexed by web crawlers.
This impacts the ranking of production content so we should instruct web crawlers to not index them.

### Requirements

Include a `<meta name="robots" content="noindex" />` tag in the dev/staging deployments to keep those URLs from being indexed by web crawlers.

### Additional information

Through https://www.google.com/search?q=site%3A5afe.dev+safe+client+gateway we can see that the [staging environment](https://safe-client.staging.5afe.dev/index.html) is being indexed

**Comment by hectorgomezv** [comment]
`X-Robots-Tag` was added to the Client Gateway **staging** response headers:

```
curl -I https://safe-client.staging.5afe.dev
HTTP/1.1 302 Found
...
X-Robots-Tag: noindex, nosnippet, noarchive
...
```

Theoretically, this will make search engines stop indexing this service in the staging environment. Thanks for reporting this @DiogoSoaress !
