### ISSUE TITLE
[Transaction deletion]When you delete a tx with the lowest nonce, the labels Next and Queued do not shift accordingly.

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-client-gateway#1387]
### Description

When you delete a tx with the lowest nonce, the labels Next and Queued do not shift accordingly.

### Reproduction steps

1. create 4 txs in queued ( example:  tx with nonce=1,2,3,4
2. delete the txs with nonce 1 and 3
Current result: The nonce of the tx 2 and 4 is not changed to 1 and 2. As result , the user has to either delete all txs to free current safe nonce or take care of the tx nonce during tx creation 
<img width="1440" alt="image" src="https://github.com/safe-global/safe-client-gateway/assets/338622/168db931-0ae8-4f08-ba90-726427a3617d">

### Expected behavior

* The "Next" label should be always the first item in the list

Make sure that the next tx after the deleted one in the queue is taking the nonce of the deleted tx

**Comment by liliya-soroka** [comment]
@katspaugh , does it mean that we will try to handle it on the front-end side and the current issue can be closed ?

**Comment by hectorgomezv** [comment]
I’d also say this is the expected behavior. Following the example in the Reproduction Steps, I’d say you need to create new transactions with nonce 1 and 3 to “unblock” the execution queue. It isn't possible to reassign the nonces, if I’m not wrong, they are used to build the transaction signature hashes so the transactions would be invalid if we change the nonces.

**Comment by katspaugh** [comment]
Yes, let's close it then. It's a smart contract limitation that nonces must be strictly sequential.

We'll restrict transaction deletion on the frontend to only allow deleting the tx with the highest nonce (see https://github.com/safe-global/safe-wallet-web/pull/3554).
