### ISSUE TITLE
docker cgw-web 500 error

### ISSUE THREAD

**Issue by supertobby** [safe-global/safe-client-gateway#1679]
### Description

I use docker compose run safe-infrastructure:
service cgw-web log error:
` {"build_number":"4d9b3a1","level":"error","message":{"chain_id":null,"client_ip":"172.31.37.10","detail":"[\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"string\",\n    \"received\": \"null\",\n    \"path\": [\n      \"results\",\n      0,\n      \"pricesProvider\",\n      \"chainName\"\n    ],\n    \"message\": \"Expected string, received null\"\n  },\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"string\",\n    \"received\": \"null\",\n    \"path\": [\n      \"results\",\n      0,\n      \"pricesProvider\",\n      \"nativeCoin\"\n    ],\n    \"message\": \"Expected string, received null\"\n  }\n]","method":"GET","origin":null,"path":"/v1/chains","response_time_ms":424.6726910000143,"route":"/v1/chains","safe_app_user_agent":null,"status_code":500},"request_id":"4a8608e6-58c0-40a4-b8a8-09d275b7b0e4","timestamp":"2024-06-21T10:53:20.167Z","version":"v1.48.0"}`

### Requirements

.

**Comment by supertobby** [comment]
in web console :
![Uploading image.png…]()

**Comment by supertobby** [comment]
on web console:
![Uploading image.png…]()

**Comment by supertobby** [comment]
on web console:
![image](https://github.com/safe-global/safe-client-gateway/assets/168184520/7bdc2571-6329-4b02-9034-f4ff3db178c8)

**Comment by lance-web3** [comment]
@supertobby hi do you found solution for this can share? thank you
