### ISSUE TITLE
Flaky PostgresDatabaseMigrator test

### ISSUE THREAD

**Issue by hectorgomezv** [safe-global/safe-client-gateway#1700]
### Description

The following error is being thrown when running `PostgresDatabaseMigrator` tests. This only happens on parallel test execution, so most likely it's due to a race condition while managing the `test` table.
```
[PostgresError: relation "test" does not exist]
```

![Screenshot 2024-06-28 at 12 30 55](https://github.com/safe-global/safe-client-gateway/assets/21182069/96628d5e-17f5-43b9-89e7-ba81293cd222)

### Reproduction steps

Run all service tests in parallel, this error happens only sometimes.

### Expected behavior

No error being thrown.

**Comment by iamacook** [comment]
On top of this (when running the tests locally) the test migration files are sometimes not deleted.
