### ISSUE TITLE
Implement tokens cache warm-up job

### ISSUE THREAD

**Issue by hectorgomezv** [safe-global/safe-client-gateway#177]
**Context**
The service needs to retrieve tokens info in a reliable and fast way. After the implementation of #166, the service will be able to query Transaction service and store each token info in a Redis hash. 

**Problem**
This retrieval and store mechanism is not performant due to the amount of non-tokens and random addresses the service receives. This causes the service to make requests to the Transaction Service for those addresses, which forces Transaction Service to retrieve the data from the blockchain at least one time for each.

Additional [context](https://github.com/safe-global/safe-client-gateway/pull/259) (Rust Client Gateway implementation).

**Proposed solution**
Warm up the cache using a scheduled job which will iterate over the [paginated token list](https://safe-transaction-mainnet.safe.global/api/v1/tokens/) returned by the Transaction Service. This job should be executed every 10 minutes. 

Keep in mind the service could be deployed in a HA setup, so several instances of the service could be running in a given point in time. Due to this, a lock mechanism is necessary. 
- This lock will be set in Redis, so both `lastExecution` (date) and `locked` (boolean) should be managed by the service.
- When a instance executes the job, it should write `lastExecution` and set `locked` to `true`.
- If an instance sees `(now() - lastExecution) < 10 minutes` and `locked == false`  the job should be started.
- After a successful run, `locked` should be set to `false`.
- A random jitter should be added to the task execution to prevent all the instances trying to execute with the same cadence.

Note: we probably need a TTL for `locked` in Redis, to prevent the scenario where a instance doesn't finish the job and never releases the lock.

**Comment by hectorgomezv** [comment]
@fmrsabino @iamacook I'm thinking of closing this one as not planned. We have been retrieving tokens one by one for a while with no issues, and we have been doing some work recently to mitigate corner cases (high amount of nested transfers, multiple parallel tokens metadata requests, etc.). So I guess this can be seen as not needed at least by now. Any concern?

**Comment by iamacook** [comment]
> @fmrsabino @iamacook I'm thinking of closing this one as not planned. We have been retrieving tokens one by one for a while with no issues, and we have been doing some work recently to mitigate corner cases (high amount of nested transfers, multiple parallel tokens metadata requests, etc.). So I guess this can be seen as not needed at least by now. Do you have any concerns regarding closing this?

I see no issue. We can revisit it if necessary.
