### ISSUE TITLE
Remove FF_CONFIRMATION_VIEW, FF_SWAPS_DECODING, FF_TWAPS_DECODING

### ISSUE THREAD

**Issue by hectorgomezv** [safe-global/safe-client-gateway#1837]
### Description

Some feature flags were added to the service to manage the availability of the Swap/Twap transaction mappings. Once these features are established, we can remove both the configuration/environment variables and the code associated with them.

### Requirements

- Delete `FF_CONFIRMATION_VIEW` along with the code associated.
- Delete `FF_SWAPS_DECODING` along with the code associated.
- Delete `FF_TWAPS_DECODING` along with the code associated.

**Comment by DrParadox05** [comment]
Hey, can I work on this?

**Comment by iamacook** [comment]
> Hey, can I work on this?

Thank you for your interest in contributing. However, this issue needs to be handled internally. Feel free to reach out on other issues in the repository. We appreciate your understanding.
