### ISSUE TITLE
chainID null

### ISSUE THREAD

**Issue by molecula451** [safe-global/safe-client-gateway#2077]
### Description

![image](https://github.com/user-attachments/assets/37744656-cef1-4d0e-a445-14a5517450e8)

chainID: 970 its always null

### Reproduction steps

Setup safe-transaction-service, add chainID 970 to the app, get null

### Expected behavior

return correct chainID

**Comment by molecula451** [comment]
@hectorgomezv

**Comment by molecula451** [comment]
hey @hectorgomezv thanks for the suggestion, the thin is I am not manually query, this is already setup within the safe-infrastructure

![image](https://github.com/user-attachments/assets/462cc793-8cba-482d-9161-f71b7b84b406)

![image](https://github.com/user-attachments/assets/39c79f4e-fff2-45cc-8df8-4c34bbb7076b)

thus when browsing the app locally I add the chainId into the app as one would expect but then because of this returns a "No Safe Deployment"

https://github.com/safe-global/safe-wallet-web/issues/4415#issuecomment-2439741980

**Comment by molecula451** [comment]
the metadata from the client gateway its not getting ready even tho the chain is added 

![image](https://github.com/user-attachments/assets/068b4173-c93f-48cb-9f36-d7eee1c9f59f)

**Comment by hectorgomezv** [comment]
I don't see any problem with the Client Gateway logs you shared in the first post. The query to the Client Gateway is sent by the web client to get all the Safes associated with the address in all the chains. This query response populates the web app sidebar that shows the Safe accounts. The message "No Safe Deployment" you are getting is not related to the Client Gateway in any way, it's related to the web client (https://github.com/search?q=org%3Asafe-global+%22No+Safe+Deployment%22&type=code), so I'm closing this to avoid duplications, the issue you opened in the web repository (https://github.com/safe-global/safe-wallet-web/issues/4415#issuecomment-2439741980) should be enough. Thanks again for reaching us!
