### ISSUE TITLE
Verify MultisigTx.origin is deserialized correctly

### ISSUE THREAD

**Issue by jpalvarezl** [safe-global/safe-client-gateway#268]
https://github.com/gnosis/safe-react/issues/836

Currently, the gw just handles a json expecting only a `url` field from which the actual `SafeAppInfo` is fetched.
https://github.com/gnosis/safe-client-gateway/blob/main/src/models/converters/transactions/safe_app_info.rs

This structure will change, it will only be a `URL` string to be returned.

Note: beware of the schema, it would be nice to be able to easily distinguish `ipfs` from `https`

**Comment by fmrsabino** [comment]
Closing this one as not planned for now. See https://github.com/safe-global/safe-react/issues/836#issuecomment-1084650983
