### ISSUE TITLE
Adjust `manifest.json` expected URL

### ISSUE THREAD

**Issue by jpalvarezl** [safe-global/safe-client-gateway#420]
## Context

https://github.com/gnosis/safe-react/issues/2403

The current state of how the gateway views a `Manifest`

```rust
#[derive(Deserialize, Debug, PartialEq)]
struct Manifest {
    pub(super) name: String,
    pub(super) description: String,
    #[serde(rename(deserialize = "iconPath"))]
    pub(super) icon_path: String,
}
```

## Feature

Adjust the `Manifest` expected structure to comply with https://web.dev/add-manifest/#create (or the subset of fields that the web app will use)

**Comment by fmrsabino** [comment]
The Safe Client Gateway no longer relies on `manifest.json`
