### ISSUE TITLE
Setup postman

### ISSUE THREAD

**Issue by rmeissner** [safe-global/safe-client-gateway#600]
Use postman for testing new and existing environments (e.g. a new L2 network) to make sure that they behave as expected

### Use cases
- [ ] E2E tests
- [ ] API documentation
- [ ] Test L2 network compatibility

**Comment by moisses89** [comment]
To this issue can help close #906 because we can import openapi.json to create a postman collection.

**Comment by fmrsabino** [comment]
Tooling will be evaluated again with the bigger migration of the Safe Client Gateway.

- E2E tests can be added to the repo.
- API docs can be generated with OpenAPI
