### ISSUE TITLE
Make Safe version nullable

### ISSUE THREAD

**Issue by hectorgomezv** [safe-global/safe-client-gateway#629]
**Problem**
_Validation errors_ are not being handled in the frontend. So when the service retrieves a Safe with a `null` version from the Transaction Service, the call to `/chains/:chainId/safes/:safeAddress` fails and the frontend is not capable of managing the error.

Failing when an _incorrect_ Safe entity (with `version: null`) is retrieved is the correct behavior, but it's not the expected one right now.

**Short-term solution**
- Make `version` a nullable field for a `Safe`. The web UI already has some logic to manage `null` Safe versions: https://github.com/safe-global/safe-wallet-web/blob/consistent-provider/src/hooks/coreSDK/safeCoreSDK.ts#L56

**Long-term solution**
- Push the implementation of a _validation error view_ in the clients, so they can manage this kind of scenario.

**Comment by hectorgomezv** [comment]
We've decided it's OK to fail on the CGW side for null versions since incorrect contract deployments (L2/nonL2 misalignment) won't be supported.

For special cases, the Safe Core team would add the contracts on demand.

**Comment by hectorgomezv** [comment]
Reopened as Safe{Core} team took the decision to make Safe `version` nullable. See: https://github.com/safe-global/safe-transaction-service/issues/1571

**Comment by fmrsabino** [comment]
> Reopened as Safe{Core} team took the decision to make Safe `version` nullable. See: [safe-global/safe-transaction-service#1571](https://github.com/safe-global/safe-transaction-service/issues/1571)

Since the `version` is already `null` on the API level I would say that we can move forward and remove this validation. The respective SDK also considers the version as `null`: https://github.com/safe-global/safe-gateway-typescript-sdk/blob/93dcd18a2738e5ccd30f803b9e39d55b9486210a/src/types/safe-info.ts#L20
