### ISSUE TITLE
Client Gateway Docs and Swagger not found

### ISSUE THREAD

**Issue by germartinez** [safe-global/safe-client-gateway#663]
**Describe the bug**
The [Client Gateway Docs](https://safe.global/safe-client-gateway/) link in the README file points to a page that does not exist.

Same happens with the [Swagger](https://safe-client.safe.global/index.html) link.

The links should be fixed or removed

**Comment by fmrsabino** [comment]
The https://safe.global/safe-client-gateway/ was based on Rust generated docs which no longer exist given the migration to Node.js.

For now there's no replacement to it and having one in a similar format is still an open question.

I will close the issue as the references to it were removed.
