### ISSUE TITLE
Implement serialisation and output DTOs

### ISSUE THREAD

**Issue by hectorgomezv** [safe-global/safe-client-gateway#68]
**Dependencies**
- [ ] Centralise schemas and data validation (TODO: link to issue)

Context [here](https://github.com/5afe/safe-client-gateway-nest/pull/66#discussion_r959772023). 

**Summary**
Currently, as shown in the context link, we have some inconsistencies between the current Client Gateway implementation responses and this new service ones. The idea here is, instead of doing ad hoc mapping in the services to the expected formats, having DTOs providing the expected payload format, and implement a serialisation layer which takes "service objects" and converts them to "presentation objects" to fulfil client's requirements.

**Note**
We could do some additional research here to see what's the best solution, but we're already using AJV to validate incoming payloads so [we could use it for serialisation as well](https://ajv.js.org/guide/getting-started.html#parsing-and-serializing-json).

**Comment by hectorgomezv** [comment]
Blocked by #69

**Comment by fmrsabino** [comment]
> Blocked by #69

More importantly. Do we need/want this. Even if the issue #69 is closed.

**Comment by hectorgomezv** [comment]
Closing this as with the pseudo automatic SDK generation @iamacook implemented, no room for inconsistencies between the CGW and its clients would be possible.
