### ISSUE TITLE
Add Chain and Safe App hook event types

### ISSUE THREAD

**Issue by fmrsabino** [safe-global/safe-client-gateway#682]
Currently chain and safe-apps related data are invalidated from the cache via the `/v2/flush` endpoint. This endpoint does not offer a lot of details on what needs to be invalidated as the payload that the Safe Client Gateway currently accepts (and receives) is:

```
{
  "invalidate": "Chains"
}
```

Since we do not know which chain we should invalidate from this payload alone, and we use the chain id as part of the redis key – `<chainId>_chain`, we need to iterate over a pattern of `*_chain` in order to invalidate the respective chain data.

We also end up invalidating chain data that did not change unnecessarily.

Scanning over a pattern in Redis can be expensive (time-wise) as it will still need to scan over the entire key set to check if it matches the respect pattern – thus the time to invalidate the cache increases linearly with the number of keys.

Invalidating Safe Apps follows the exact same flow (with the same payload).

## Proposal

Extend the `POST /v1/hooks/events` endpoint to accept the following new payloads:

```
{
  "type":  "CHAIN_UPDATE"
  "chain": <chainId>
}
```

and

```
{
  "type":  "SAFE_APPS_UPDATE"
  "chain": <chainId>
}
```

The payload with type `CHAIN_UPDATE` should be used to invalidate the Chain cache of `chainId` only while the `SAFE_APPS_UPDATE` type should be used to invalidate the Safe Apps cache of `chainId` only.

## Future work

If the above proposal is implemented, `POST /v2/flush` can be removed as long as the clients using this endpoint migrate to `POST /v1/hooks/events` it (i.e.: Safe Config Service).

**Comment by Uxio0** [comment]
I like the proposal of having a `type` for flushing concrete data, as long as it's well documented what event comes from what  service.

> Scanning over a pattern in Redis can be expensive (time-wise) as it will still need to scan over the entire key set to check if it matches the respect pattern – thus the time to invalidate the cache increases linearly with the number of keys.

Regarding this, there are workarounds that shouldn't limit the implementation:
- In previous projects what I have been doing is keeping a `List`` pointing to the keys. So for example, if I'm supposed to keep `DATA-1` and `APPS-1` keys for `chainId` 1, I will also keep a `List chainId-1` where I store `[DATA-1, APPS-1]`, so when I'm supposed to delete everything related to `chainId 1` I iterate that Redis List and delete everything, even using a LUA script to prevent the back and forth.
- You could even optimize the current SCAN optimization via a LUA script so you don't need to do `SCAN`, then `iterate` and then `delete`, doing everything on the server
- You could use different Redis namespaces, for example keeping `transaction-service` related stuff on the namespace `1` and `config-service` related stuff on namespace `2`, so `SCAN` is faster

There are multiple workarounds to prevent taking decisions depending on the `SCAN` implementation. By te the way, in the current version I don't see any warnings related to SCAN, and `O(n)` for a complete iteration looks quite decent, you could test the speed in a production environment.

**Comment by fmrsabino** [comment]
> I like the proposal of having a `type` for flushing concrete data, as long as it's well documented what event comes from what service.

At the moment we have `/v2/flush` which was only being used by the Safe Config Service and `/v1/hooks/events` which is used by the Safe Transaction Service.

I think this distinction does not make a lot of sense at the moment (at the time that `/v2/flush` was implemented it was mostly to have an HTTP admin route to clear the Redis cache).

The motivation for this issue is that we can further standardise the hooks, since we already have a `type` which is the contract between the Safe Transaction Service and the Safe Client Gateway we can extend this contract to the Safe Config Service.

The new Web Hook types could potentially be used by the Safe Transaction Service or Safe Events Service if needed.

> > Scanning over a pattern in Redis can be expensive (time-wise) as it will still need to scan over the entire key set to check if it matches the respect pattern – thus the time to invalidate the cache increases linearly with the number of keys.
> 
> Regarding this, there are workarounds that shouldn't limit the implementation:
> 
> * In previous projects what I have been doing is keeping a `List` pointing to the keys. So for example, if I'm supposed to keep `DATA-1` and `APPS-1` keys for `chainId` 1, I will also keep a `List chainId-1` where I store `[DATA-1, APPS-1]`, so when I'm supposed to delete everything related to `chainId 1` I iterate that Redis List and delete everything, even using a LUA script to prevent the back and forth.

This is an interesting idea (it would need some other changes on the Safe Client Gateway but totally doable). We do use Hashes for most of the invalidations (except for the Safe Config related data). We could have the list in a Redis SET and iterate over that set only.

> * You could even optimize the current SCAN optimization via a LUA script so you don't need to do `SCAN`, then `iterate` and then `delete`, doing everything on the server.

Do you have any references to this part? The Webhooks that we are receiving from the Safe Config Service don't have any information on which chain to invalidate that's why we triggered a `SCAN` there. From my perspective we always need to get the exact keys that match a pattern so that would always result in something similar to `SCAN`.

> * You could use different Redis namespaces, for example keeping `transaction-service` related stuff on the namespace `1` and `config-service` related stuff on namespace `2`, so `SCAN` is faster

This is an interesting idea which I think would work really well for `SCAN` and `/v2/flush`. But given the way that we use `/v2/flush` and since we have the required information on which chain we should invalidate the data from I think extending `/v1/hooks/events` and deprecate `/v2/flush` makes more sense.

> There are multiple workarounds to prevent taking decisions depending on the `SCAN` implementation. [By the way, in the current version I don't see any warnings](https://redis.io/commands/scan/) related to SCAN, and `O(n)` for a complete iteration looks quite decent, you could test the speed in a production environment.

I have gathered some data using a dump of the Redis state from production and an invalidation using `SCAN` was taking around 30 seconds it was not causing any issues with the service itself but it's a really long time for the callers (who might timeout).

**Comment by Uxio0** [comment]
> The new Web Hook types could potentially be used by the Safe Transaction Service or Safe Events Service if needed.

Sure thing! What I mean is as the event types does not hold a namespace, maybe at some point it becomes complicated to know what events come from which service, so we should keep it very well documented.

> Do you have any references to this part? The Webhooks that we are receiving from the Safe Config Service don't have any information on which chain to invalidate that's why we triggered a SCAN there
What I meant is that you need to do SCAN, but instead of getting the keys in the backend and call Redis again with the keys, you can do everything in the server: https://stackoverflow.com/questions/61366419/how-to-atomically-delete-millions-of-keys-matching-a-pattern-using-pure-redis

> This is an interesting idea which I think would work really well for SCAN and /v2/flush. But given the way that we use /v2/flush and since we have the required information on which chain we should invalidate the data from I think extending /v1/hooks/events and deprecate /v2/flush makes more sense.

Agree

> I have gathered some data using a dump of the Redis state from production and an invalidation using SCAN was taking around 30 seconds it was not causing any issues with the service itself but it's a really long time for the callers (who might timeout).

That's good data, we should stay aways from `SCAN` then as it even blocks the server. With this information I would try:
- Invalidation using SCAN + DELETE via a LUA script, check how long it takes.
- If it takes a lot, I think the viable option is keeping this *list of pointers* I was taking about

**Comment by fmrsabino** [comment]
I don't know how LUA can help us here if the underlying operation is the same though 🤔 Or are you suggesting that the Redis Client that we use might impede the performance even further while using the `SCAN` command?

One change that I'd propose to the payloads above would be to turn the `chain` into a collection of Chain IDs. This way we can invalidate multiple chains if needed without triggering multiple Webhooks.

```
{
  "type":  "CHAIN_UPDATE"
  "chainIds": [<chainId>]
}
```

**Comment by hectorgomezv** [comment]
There are some great ideas in the issue and its comments! I agree this part can be improved in several ways. I'm totally in favor of breaking down the `/v2/flush/` endpoint functionality into more granular use cases. That would bring clarity for both the clients and the service's own implementation. 

> I have gathered some data using a dump of the Redis state from production and an invalidation using `SCAN` was taking around 30 seconds it was not causing any issues with the service itself but it's a really long time for the callers (who might timeout).

I assume you are triggering an invalidation locally (both the CGW and Redis running in local containers). I suppose the networking back-and-forth is more expensive in production (even if the containers are in the same cluster, they could be in different nodes). I think @Uxio0 was suggesting a Lua script solution because networking time could be the bottleneck as we are iterating and invalidating items one by one here: https://github.com/safe-global/safe-client-gateway/blob/b51e6a119083aaed04c07cca61cf18ffd3db5d8e/src/datasources/cache/redis.cache.service.ts#L54

I'd start by breaking down the invalidation into smaller targets (by chainId) as @fmrsabino suggests, and then we could try to improve that invalidation code by decreasing the network back and forth by sending several keys at once (batching them maybe?). I also like the 2-level cache @Uxio0 suggested (using sets of keys), it's a nice next step if we still facing performance issues here.

**Comment by Uxio0** [comment]
> I don't know how LUA can help us here if the underlying operation is the same though 🤔 Or are you suggesting that the Redis Client that we use might impede the performance even further while using the SCAN command?

If you are looking for invalidating keys recovered with `SCAN`, the current flow is:
- Use SCAN on the server, and get the keys in the client
- Call the server again with the keys to remove

If you use `LUA`:
- Use a script that removes the keys returned by `SCAN`

> I assume you are triggering an invalidation locally (both the CGW and Redis running in local containers). I suppose the networking back-and-forth is more expensive in production (even if the containers are in the same cluster, they could be in different nodes). I think @Uxio0 was suggesting a Lua script solution because networking time could be the bottleneck as we are iterating and invalidating items one by one here:

Yes, this 😉 

> I'd start by breaking down the invalidation into smaller targets (by chainId) as @fmrsabino suggests, and then we could try to improve that invalidation code by decreasing the network back and forth by sending several keys at once (batching them maybe?). I also like the 2-level cache @Uxio0 suggested (using sets of keys), it's a nice next step if we still facing performance issues here.

Agree

**Comment by fmrsabino** [comment]
I misunderstood what you were saying @Uxio0. It makes sense yes 👍 

But given that we have the ability right now to change the payload itself I'd say that the better solution would involve removing `/v2/flush` and work with more granular data on what needs to be invalidated.

I would say that we should keep your proposal in mind if, for example, we want to invalidate all Safe Info data (i.e. collective keys that we are not grouping at the moment).

**Comment by Uxio0** [comment]
> But given that we have the ability right now to change the payload itself I'd say that the better solution would involve removing /v2/flush and work with more granular data on what needs to be invalidated.

Totally agree. I was just giving ideas for th future. 😉

**Comment by fmrsabino** [comment]
> One change that I'd propose to the payloads above would be to turn the `chain` into a collection of Chain IDs. This way we can invalidate multiple chains if needed without triggering multiple Webhooks.
> 
> ```
> {
>   "type":  "CHAIN_UPDATE"
>   "chainIds": [<chainId>]
> }
> ```

In https://github.com/safe-global/safe-config-service/pull/964 I've decided to not have a collection of chain ids to follow the same structure set by the Safe Transaction Service (now Safe Events Service).

This can still be considered in the future but I'd be more in favour that the Safe Events Service would start using a collection too.
