### ISSUE TITLE
Safe doesn't load on goerli after specific tx

### ISSUE THREAD

**Issue by tschubotz** [safe-global/safe-client-gateway#690]
## Bug description

Safe doesn't load anymore.

## Environment
 - Browser: Chrome
 - Wallet: -
 - Chain: Goerli

## Steps to reproduce
1. Open https://app.safe.global/balances?safe=gor:0x9a3227589F7dBDb9f006bACE1383e5e4939dA6CC

## Expected result

Safe is opened

## Obtained result

Not possible to open. Client gateway returns a [500](https://safe-client.safe.global/v1/chains/5/safes/0x9a3227589F7dBDb9f006bACE1383e5e4939dA6CC
) (Should this bug be transferred to the CGW repo then?) 

## Screenshots

<img width="721" alt="image" src="https://github.com/safe-global/safe-wallet-web/assets/1380529/fc4a8de1-371d-4534-b959-0e428c2ec88c">

## Details

This bug was reported at DappCon. It's reproducible for them. They always create 1 Safe, make 1 tx and then the Safe doesn't load anymore. 

The "1 tx" for the Safe above was: https://goerli.etherscan.io/tx/0x9338f8d95210f7325f6bf06cc555dfd017e5cc4819a73bd32ef69b22abe02bae

I have a contact via TG, in case we need more details.

**Comment by fmrsabino** [comment]
> I've debugged this a little. This Safe has a spending limit module enabled for which the tx service cannot fetch a tx history which CGW needs for some reason to fetch the Safe info. So ultimately CGW returns a 500 for the Safe info.

The modules are used to compute the `txHistoryTag`

> I think CGW shouldn't return a 500 in any case, as it's very obscure to the client and is the equivalent of an uncaught exception. And maybe it shouldn't fail to load a Safe info only because its module tx history cannot be fetched?

I agree. It should not fail and the `txHistoryTag` should return a value that takes into account the other endpoints already being used (multisig-transactions and transfers).
