### ISSUE TITLE
`InfoProvider` hardcoded `limit` for tokens request

### ISSUE THREAD

**Issue by jpalvarezl** [safe-global/safe-client-gateway#830]
## Problem
The CGW token info cache is populated in the following [method](https://github.com/gnosis/safe-client-gateway/blob/541dd3f07fe5cea474b322772779462640354f32/src/providers/info.rs#L262)

Implementing the hotfix for this issue #828 we decided to extract the value into an environment variable. However, this solution isn't permanent, as our services add tokens automatically, which in time, will once again increase the list size to a point that our assumption is no longer valid.

## TODO

Draft a permanent solution proposal.

**Comment by fmrsabino** [comment]
We will consider this for the bigger ongoing refactor of the Safe Client Gateway.
