### ISSUE TITLE
Add a `simulate` endpoint proxying simulation requests to Tenderly

### ISSUE THREAD

**Issue by mikheevm** [safe-global/safe-client-gateway#836]
**Is your feature request related to a problem? Please describe.**
As a part of https://github.com/gnosis/safe-react-apps/issues/200, we would like to use Tenderly for integrating transaction simulation into the Transaction Builder Safe App. The Tenderly endpoint uses a token-based authentication from the request header. We need to hide the token behind a proxy not to expose our token.

**Provide references to the feature you are implementing that requires this change**
https://github.com/gnosis/safe-react-apps/issues/200

**Describe the solution you'd like**
A new endpoint `simulate` endpoint accepts the same data as Tenderly's `simulate` endpoint. Perhaps We could put it under the `transaction` route. It would return an object with the following structure:
```
{
  "uri": "Link to the simulation (tenderly in this particular case)",
  "data": tenderly simulate endpoint response
}
```
The endpoint should be rate-limited and restricted to the `gnosis-safe.io` domain.

**Describe alternatives you've considered**
Directly calling Tenderly API, but it'd expose our token.

**Example payload**
```json
{
    "network_id": "1",
    "block_number": 15107216,
    "transaction_index": 1,
    "from": "0x0000000000000000000000000000000000000012",
    "to": "0x0000000000000000000000000000000000000000",
    "input": "0x",
    "gas": 10000000,
    "gas_price": "0",
    "value": 0,
    "save": true,
    "generate_access_list": true,
    "save_if_fails": false,
    "state_overrides": {
    "0x852382664894Ce9beFBcf72940b3CdcD7eAbfeb0": {
        "storage": {
            "0x0000000000000000000000000000000000000000000000000000000000000002": "0x0000000000000000000000000000000000000000000000000000000000000001"
           }
       }
    }
}
```
For the full payload explanation please check the tenderly docs below

**Additional context**
[Tenderly docs](https://www.notion.so/Simulate-API-Documentation-6f7009fe6d1a48c999ffeb7941efc104)
[Obtaining authentication token for Tenderly](https://www.notion.so/Authenticating-with-the-Tenderly-API-d9b224b1508f4da8b80b00f2a132d291)

**Generating an Access Token through the UI**
To get your Access Token go to the **Account > Authorization** part of your [Tenderly dashboard](https://dashboard.tenderly.co/account/authorization) and click on **Generate Access Token**.

**Authenticating with the Access Token**
When making API requests add the `X-Access-Key` header with the value `{{token}}`.

**Open questions**
- This feature could not be available on some networks, e.g. Aurora. Should we put this as a feature on the config service? The web team might also integrate with tenderly in the future
- What would be a reasonable rate limit? I'd say 3 simulations per 60 secs is ok

**Comment by rmeissner** [comment]
I would not call it `tenderly_link` but rather something more generic, as the UI doesn't have to know that implementation detail. Maybe just `uri` would do.

**Comment by rmeissner** [comment]
Potentially it might make sense to have a light weight proxy service independent of the client gateway (similar to our rpc proxies). The client gateway does not have logic domain restriction and also the rate limit logic is not used (we experimented with it in the past).

**Comment by rmeissner** [comment]
Also can you please specify how the token should be added and where we can acquire the token

**Comment by rmeissner** [comment]
The account creating the access token should be a paid account to avoid that we run into limits (see https://tenderly.co/pricing/)

**Comment by mikheevm** [comment]
Relaying what we've discussed internally in slack:
Instead of adding an endpoint to the client gateway, we implement an Nginx proxy to the tenderly API
