### ISSUE TITLE
[Polygon] Support Official USDC coin deployment

### ISSUE THREAD

**Issue by JABirchall** [safe-global/safe-client-gateway#857]
## What is the feature about
Last month Circle added polygon to their official supported chains and deployed the official USDC token on the network.
Safe currently does no recognize the official USDC token.

## The list of requirements
Support fetching the price of the official USDC token on polygon
Address: 0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359

Rename the bridged USDC symbol to USDC.e
Renamed the bridged USDC token name to USD Coin (PoS)
Address: 0x2791bca1f2de4661ed88a30c99a7a9449aa84174

## Designs/sketches
![](https://i.imgur.com/v3b17Ay.png)

## Links
Announcement https://www.circle.com/blog/announcing-support-for-polygon-usdc
Officla USDC Deployment https://polygonscan.com/token/0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359
Bridged USDC.e Deployment https://polygonscan.com/token/0x2791bca1f2de4661ed88a30c99a7a9449aa84174

Clone of
https://github.com/safe-global/safe-transaction-service/issues/1743
https://github.com/safe-global/safe-wallet-web/issues/2743

**Comment by fmrsabino** [comment]
Hey @JABirchall thanks for reporting the issue and apologies for the back and forth that you had on this one.

We were doing a migration on the price providers early November and the issue seems to be fixed now so I will close it.

**Comment by JABirchall** [comment]
> Hey @JABirchall thanks for reporting the issue and apologies for the back and forth that you had on this one.
> 
> We were doing a migration on the price providers early November and the issue seems to be fixed now so I will close it.

Its ok, its hard to know what are the correct repos to post issues too.

**Comment by fmrsabino** [comment]
> Its ok, its hard to know what are the correct repos to post issues too.

Your initial report is totally ok since the context was what was shown on the Web UI. But in general, if the issue belongs to a different repository inside `safe-global` we can take the transfer of the ticket ourselves.

Thank you for following up with this report. We will try to improve this on our side.
