### ISSUE TITLE
[Safe Apps]. Support for `icons` property in the manifest.json file

### ISSUE THREAD

**Issue by yagopv** [safe-global/safe-client-gateway#862]
### Is your feature request related to a problem? Please describe
Safe Apps made changes in the required `manifest.json` file in order to improve the web standards support. We now can support the `icons` [property](https://developer.mozilla.org/en-US/docs/Web/Manifest/icons) besides  the `iconPath` one. 

### Provide references to the feature you are implementing that requires this change
- [Safe Apps changes for support icons](https://github.com/safe-global/safe-react-apps/issues/329)

### Describe the solution you'd like
We would like the safe-client-gateway to be [updated](https://github.com/safe-global/safe-client-gateway/blob/1c52acd5dae1615064bfd29b5d78559684344869/src/providers/info.rs#L152) the same way so images can be extracted from the `icons` property with a fallback to the `iconPath`.

For us the best option should be to ADD support for the `icons` and return the prop as it is (the complete array) while maintaining the current support for `iconPath`, taking into account the old apps are going to send `iconPath` and the new ones `icons` so perhaps some error logic will be necessary.

#### Additional context
- [Bug, restoring iconPath](https://github.com/safe-global/safe-react-apps/pull/418)
- [Safe React changes](https://github.com/safe-global/safe-react/pull/3684)

We are currently trying to find the [best image](https://github.com/safe-global/safe-react/blob/d1a20f04f7e4c46d8edff45fb8be7580c504dfe5/src/routes/safe/components/Apps/utils.ts#L128) we can inside the `icons` array:

1) Trying to find a vector (svg) or something the app indicates that fits any size (any)
2) Trying to find some image bigger than 128px
3) Fallback to whatever is present

**Comment by rmeissner** [comment]
Note:
- SVGs are not supported by Android out of the box

Questions:
- Should we return the array of images and the clients identify the appropriate image themselves?
- Would it be an alternative to ignore the manifest information for apps that are not listed in the config service?

**Comment by yagopv** [comment]
Notes for the sync:

- Gateway => If we return a new `icons` prop and maintain the compatibility with the current one (Same thing we did) then no dependencies are necessary with other projects for start the develop.  A ticket can be opened in mobile and web for start using the new returned property and choose the right icon.
- Config Service configuration for safe apps is really manual so the icon is added per app choosing the right one provided in the manifest (Should talk about SVGs because there are several apps providing only an SVG)

**Comment by rmeissner** [comment]
Proposed solutions:
- Remove support for the manifest in the client gateway and only rely on the config service
- Search for the icon that satisfies our requirements
- Return `icons` to the clients and handle it there
