### ISSUE TITLE
Executed transactions are displayed in queued 

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-client-gateway#897]
**Describe the bug**
Couple of users have reported that after executing transaction using the web interface it still displayed in the queued list.
**Expected behavior**
After executing transaction is should displayed in History 
**Environment**
 - Production
 - Mainnet
 - macOS 
 - Chrome

**Additional context**
Here is one of the affected safe: 

Intercom: https://app.intercom.com/a/apps/km54f6ih/inbox/inbox/5304360/conversations/36000013113
Safe: https://gnosis-safe.io/app/eth:0x67F60b0891EBD842Ebe55E4CCcA1098d7Aac1A55/transactions/queue
Tx hash: https://etherscan.io/tx/0xe592c244d7fd5fcf40f86388f991efaee3b56f31ace8e91f01909d194b632168

Also this two safes had the same issue but the problem was solved after waiting for some time:

First safe:
Intercom: https://app.intercom.com/a/apps/km54f6ih/inbox/inbox/5304360/conversations/36000013115
Safe: https://gnosis-safe.io/app/eth:0x9e6c1174a341f95Cd4F1c7d4eedfFE9Fb2F3Db2A/transactions/queue

Second safe:
Intercom: https://app.intercom.com/a/apps/km54f6ih/inbox/inbox/unassigned/conversations/36000013123
Safe:https://gnosis-safe.io/app/eth:0xdc08c0d582894214ec704108b6750b58b241A5D1/transactions/queue

**Comment by MouazAlzahabi** [comment]
Another user reported the same issue afterward but on BSC 
intercom: https://app.intercom.com/a/apps/km54f6ih/inbox/inbox/unassigned/conversations/36000013159

Safe: https://gnosis-safe.io/app/bnb:0x085d8724A16E874eCd8033bE6B7e7E3755Ea1725/transactions/queue

**Comment by fmrsabino** [comment]
> Another user reported the same issue afterward but on BSC intercom: https://app.intercom.com/a/apps/km54f6ih/inbox/inbox/unassigned/conversations/36000013159
> 
> Safe: https://gnosis-safe.io/app/bnb:0x085d8724A16E874eCd8033bE6B7e7E3755Ea1725/transactions/queue

This is not an L2 Safe (master copy of this proxy is: `0xd9Db270c1B5E3Bd161E8c8503c55cEABeE709552` which we currently do not support.

The only master copy that we support on Binance is `0x3E5c63644E683549055b9Be8653de26E0B4CD36E`
