### ISSUE TITLE
Include to swagger missing endpoints.

### ISSUE THREAD

**Issue by moisses89** [safe-global/safe-client-gateway#913]
This endpoints that include a lifetime are not supported by okApi:

        contracts::routes::post_data_decoder,
        notifications::routes::post_notification_registration,
        safes::routes::post_safe_gas_estimation,
        safes::routes::post_safe_gas_estimation_v2,
        transactions::routes::post_confirmation,
        transactions::routes::post_transaction

example:

```
#[post(
    "/v1/chains/<chain_id>/data-decoder",
    format = "application/json",
    data = "<data_decoder_request>"
)]
pub async fn post_data_decoder<'e>(
    context: RequestContext,
    chain_id: String,
    data_decoder_request: Result<Json<DataDecoderRequest>, Error<'e>>,
) -> ApiResult<content::RawJson<String>> {
    Ok(content::RawJson(serde_json::to_string(
        &handlers::request_data_decoded(&context, &chain_id, &data_decoder_request?.0).await?,
    )?))
```

Related issue:
https://github.com/GREsau/okapi/issues/84 

This issue should be close when this endpoints are added.

**Comment by fmrsabino** [comment]
This will be done in the context of the bigger refactor. It is also a requirement for the new refactor.

I'm leaving the issue open until that is done.

**Comment by fmrsabino** [comment]
@moisses89 I'm thinking about closing this issue actually since it is a requirement for the bigger refactor of the Safe Client Gateway.

I think it's better to use this issue board for current ongoing issues that need to be fixed (and not "quality-of-life" improvements for the current version of the Safe Client Gateway).

**Comment by moisses89** [comment]
Yes make sense this is currently no planned.
