### ISSUE TITLE
Add links to Swagger and Rust types to Readme

### ISSUE THREAD

**Issue by katspaugh** [safe-global/safe-client-gateway#917]
Please add links to Swagger and Rust types (https://safe.global/safe-client-gateway/docs/routes/index.html) in the Readme and the repo description.

<img width="343" alt="Screenshot 2022-07-10 at 10 08 16" src="https://user-images.githubusercontent.com/381895/178136672-6f60120f-c987-494c-9931-8e1c5bfdf978.png">

**Comment by fmrsabino** [comment]
> Please add links to Swagger and Rust types (https://safe.global/safe-client-gateway/docs/routes/index.html) in the Readme 

If by Rust types you mean the generated docs by Rust this was already present in the README https://github.com/safe-global/safe-client-gateway#documentation 😄
