### ISSUE TITLE
Add paginated endpoint for collectibles

### ISSUE THREAD

**Issue by moisses89** [safe-global/safe-client-gateway#920]
**Is your feature request related to a problem? Please describe.**
Long lists of collectibles ERC720 takes a lot of time to return to the client.   
 
- https://github.com/safe-global/safe-pm/issues/89

**Describe the solution you'd like**
Include a new version of endpoint to support pagination of transaction service   
- https://github.com/safe-global/safe-transaction-service/issues/239

**Comment by katspaugh** [comment]
Question: will this be a new endpoint or a breaking change on the existing one?

**Comment by moisses89** [comment]
I think that should be a new version like /v2/chains/... To avoid issues with other clients in production.
