### ISSUE TITLE
Swagger: add response types

### ISSUE THREAD

**Issue by katspaugh** [safe-global/safe-client-gateway#928]
Posting here as per @FahdSaif's request.

The swagger currently only shows the shapes of the requests but not the responses.

**Comment by moisses89** [comment]
I think that this is related with this issue. 
https://github.com/GREsau/okapi/issues/102

**Comment by fmrsabino** [comment]
This will be done in the context of the bigger refactor. It is also a requirement for the new refactor.

I'm leaving the issue open until that is done.

**Comment by fmrsabino** [comment]
We have decided to close this issue in favour of https://github.com/5afe/safe-client-gateway-nest/issues/76

Swagger implementation and response types will be tackled under that new issue.
