### ISSUE TITLE
/v1/balances/supported-fiat-codes 401 code

### ISSUE THREAD

**Issue by masayil** [safe-global/safe-client-gateway#944]
![image](https://user-images.githubusercontent.com/65291464/183567484-426de03b-bb17-4a9b-8076-48ea22ac4ab3.png)

**Comment by fmrsabino** [comment]
Endpoint seems to be working as expected: https://safe-client.gnosis.io/v1/balances/supported-fiat-codes

**Comment by masayil** [comment]
It is my private gateway client.

**Comment by masayil** [comment]
> Endpoint seems to be working as expected: https://safe-client.gnosis.io/v1/balances/supported-fiat-codes

It is my private gateway client. 
Where does this API KEY need to be set？

**Comment by fmrsabino** [comment]
> > Endpoint seems to be working as expected: https://safe-client.gnosis.io/v1/balances/supported-fiat-codes
> 
> It is my private gateway client. Where does this API KEY need to be set？

Here are the two variables that you need to set it up: https://github.com/safe-global/safe-client-gateway/blob/b50db3afeb6ba91d498f5362343e88bd241deac6/.env.sample#L82-L84

**Comment by masayil** [comment]
> EXCHANGE_API_BASE_URI=http://api.exchangeratesapi.io/latest

 EXCHANGE_API_BASE_URI=http://api.exchangeratesapi.io/latest

**Comment by fmrsabino** [comment]
> EXCHANGE_API_KEY

I'm sorry but I don't understand completely what the issue seems to be.

You need to set the API key that you'll use under `EXCHANGE_API_KEY`. You can get one at https://exchangeratesapi.io/

**Comment by masayil** [comment]
> > EXCHANGE_API_KEY
> 
> I'm sorry but I don't understand completely what the issue seems to be.
> 
> You need to set the API key that you'll use under `EXCHANGE_API_KEY`. You can get one at https://exchangeratesapi.io/

yeah. I have got one free key.  The default value of `EXCHANGE_API_BASE_URI` is `http://api.exchangeratesapi.io/latest`. Do I change it ?

**Comment by fmrsabino** [comment]
> yeah. I have got one free key. The default value of `EXCHANGE_API_BASE_URI` is `http://api.exchangeratesapi.io/latest`. Do I change it ?

No need to change it.
