### ISSUE TITLE
Process contract/token webhooks

### ISSUE THREAD

**Issue by Uxio0** [safe-global/safe-client-gateway#971]
Contract and token webhooks should be processed invalidating contract/token cache when transaction service starts sending them.

Related to https://github.com/safe-global/safe-transaction-service/issues/1082

**Comment by fmrsabino** [comment]
For invalidating all the contracts cache this is already possible by doing something like:

```
curl --location --request POST 'https://localhost:8080/v2/flush' \
--header 'Content-Type: application/json' \
--data-raw '{
    "invalidate": "Contracts"
}'
```

And for invalidating the token related cache you can do the following:

```
curl --location --request POST 'https://[safe-client.staging.gnosisdev.com](localhost:8080)/v2/flush' \
--header 'Content-Type: application/json' \
--data-raw '{
    "invalidate": "Tokens",
    "pattern_details": {
        "chain_id": "4"
    }
}'
```

**Comment by Uxio0** [comment]
Sure @fmrsabino , but I was talking about processing webhooks the same way we do it with new transactions or new confirmations, not using admin endpoints 😉

**Comment by fmrsabino** [comment]
> Sure @fmrsabino , but I was talking about processing webhooks the same way we do it with new transactions or new confirmations, not using admin endpoints 😉

I don't think these are considered admin endpoints. The Config Service uses these for the hooks. But if we want to change that we can discuss!

**Comment by fmrsabino** [comment]
Closing this issue as it no longer applies in this context. But we can open a new discussion under https://github.com/safe-global/safe-client-gateway-nest if it makes sense.
