### ISSUE TITLE
[Arbitrum]Diff statuses for the same tx in the ../transactions/history and ../42161/transactions/id end points

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-client-gateway#989]
**Describe the bug**
Diff statuses for the same tx in the ../transactions/history and ../42161/transactions/id end points

**To Reproduce**
1. https://safe-client.safe.global/v1/chains/42161/safes/0x861099a9FD94b03471a1002efCa662c3ECAdB10C/transactions/history
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/338622/198566061-127b5182-7824-4190-919b-0fbca6460562.png">
tx status = success

2. https://safe-client.safe.global/v1/chains/42161/transactions/multisig_0x861099a9FD94b03471a1002efCa662c3ECAdB10C_0xe0dd3bb1265f38d472c1aa07ca281c99bccb281fdf56eb9e847a017794aa1ea8
<img width="998" alt="image" src="https://user-images.githubusercontent.com/338622/198566178-6f6b78c4-bc60-4470-8b19-6e45bed16313.png">
tx status = cancelled

The wrong status stays for quite a long time, which causes UI issues for the clients 
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/338622/198566393-db0f49d6-fe1c-401c-a191-95a790cd3165.png">
<img width="521" alt="image" src="https://user-images.githubusercontent.com/338622/198566514-1a6ffd8a-39a1-4691-8432-c20828fa8fe4.png">
<img width="711" alt="image" src="https://user-images.githubusercontent.com/338622/198566577-fde21a6c-ea3b-4679-a6b9-534fb830268c.png">

**Expected behavior**

**Environment (please complete the following information):**
 - production
 - Arbitrum
 - OS: both clients
 - Browser Chrome

**Additional context**

**Comment by fmrsabino** [comment]
Thanks for reporting. Issue was related with caching and it was fixed.

Closing it.
